geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path
from ordersapp import views

app_name = 'ordersapp'

urlpatterns = [
    path('', views.OrderList.as_view(), name='orders_list'),
    path('read/<pk>/', views.OrderItemsView.as_view(), name='order_read'),
    path('update/<pk>/', views.OrderItemUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', views.OrderItemsDelete.as_view(), name='order_delete'),
    path('create/', views.OrderItemCreate.as_view(), name='order_create'),
    path('forming/complete/<pk>', views.order_forming_complete, name='order_forming_complete'),
]

users/urls.py
from django.urls import path
from users.views import login, registration, logout, profile, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/<email>/<activation_key>', verify, name='verify')
]

ordersapp/models.py
from django.db import models
from django.db.models.base import Model
from django.conf import settings
from django.db.models.deletion import CASCADE
from products.models import Product

# Create your models here.


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    DELIVERY = 'DLV'
    DONE = 'DN'
    CANCELED = 'CNC'

    STATUSES = (
        (FORMING, 'формирование'),
        (SENT_TO_PROCEED, 'передан в обработку'),
        (DELIVERY, 'доставка'),
        (DONE, 'выдан'),
        (CANCELED, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, default=FORMING, max_length=3)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created', )

    def __str__(self):
        return f'Заказ номер {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost, items)))

    def delete(self):
        self.is_active = False
        self.save()


class OrderItemQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super().delete(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    objects = OrderItemQuerySet.as_manager()

    @property
    def get_product_cost(self):
        return self.quantity * self.product.price

    def delete(self):
        self.product.quantity += self.quantity
        self.product.save()
        super().delete()

    def save(self, *args, **kwargs):
        if self.pk:
            self.product.quantity -= self.quantity - \
                self.__class__.get_item(self.pk).quantity
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super().save(*args, **kwargs)

ordersapp/forms.py
from django import forms

from .models import Order, OrderItem


class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False, max_length=50)

    class Meta:
        model = OrderItem
        exclude = ()
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

ordersapp/views.py
from django.http import request
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views.generic.edit import DeleteView
from ordersapp.forms import OrderItemForm
from django.db import models
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.db import transaction

from ordersapp.models import Order, OrderItem
from baskets.models import Basket


# Create your views here.
class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.method == 'POST':
            formset = OrderFormset(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if basket_items.exists():
                OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=basket_items.count())
                formset = OrderFormset()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormset()


        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
                basket_items = Basket.objects.filter(user=self.request.user)
                basket_items.delete()

        return super().form_valid(form)

class OrderItemUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.method == 'POST':
            formset = OrderFormset(self.request.POST, instance=self.object)
        else:
            formset = OrderFormset(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price


        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()


        return super().form_valid(form)


class OrderItemsDelete(DeleteView):
    model = Order
    success_url = reverse_lazy("ordersapp:orders_list")


class OrderItemsView(DetailView):
    model = Order


def order_forming_complete(request, pk):
    order_item = get_object_or_404(Order, pk=pk)
    order_item.status = Order.SENT_TO_PROCEED
    order_item.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))

ordersapp/templates/ordersapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
        {% block content %}
        {% endblock %}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>

</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {{ field }}
                                {% else %}
                                    {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб.
                                    {% endif %}
                                {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
            {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'products:index' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'ordersapp:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}